name: Build and Deploy Glog Reader to Azure

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 3️⃣ Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 4️⃣ Build the project (skip tests for faster deploy)
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 5️⃣ Azure login using Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 6️⃣ Deploy JAR file to Azure Web App (F1)
      - name: Deploy JAR to Azure Web App
        run: |
          az webapp deploy \
            --resource-group rg-lab \
            --name glog-reader \
            --type jar \
            --src-path target/glog-reader-0.0.1-SNAPSHOT.jar
